create table if not exists public.concerts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,

  artist       text        not null,
  venue        text        not null,
  date         date        not null,
  genre        text        not null,
  ticket_price numeric(10,2),
  status       text        not null default 'Want to Go'
                 check (status in ('Want to Go', 'Got Tickets', 'Attended')),
  notes        text
);

alter table public.concerts enable row level security;

create policy "concerts_select_anyone"
  on public.concerts for select
  using (true);

create policy "concerts_insert_authenticated"
  on public.concerts for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "concerts_update_owner"
  on public.concerts for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "concerts_delete_owner"
  on public.concerts for delete
  to authenticated
  using (auth.uid() = user_id);